language: java
install: skip

os: linux
dist: trusty
jdk: openjdk11

addons:
  sonarcloud:
    organization: "zakgof"
    token:
      secure: "UmcKUI+AbMkKHi4gOe3c6TnO6j9fIaHvxIQI/iXfX+P05VYsPqxyzJlgK9XatnY1oMMilSvkoAxw3JWlm8KGbymaMPuaJfhCkPYainR91mOLimblkUzZah1W0nMXpSu8rnoEHDIgGjstFzSveOHRk/p9d4IFMkgIWLRx5ZmwlPEsM9yOSmMpuqDU+Wl5YoKn0JxDCmrdkA+CtlyQpuCMB/oEk0eZWc9WtCJpT305IvgfzjroDoIs4pntjyQ/zf91qcm/fncvKkjErshHLW36OCZWplQsniMKVHpq1dcJgF0Y3i42IYuZMd5yrXuftXsfU/XbOLrdVBmlHPewORBBNLasvagN7Iz5JGv5N+CCoVigU9EhCG1ypyHbyTUWN56V+64HVrRxONRPvGc+Lp9P1X6cGyQWMvRWr7hM7ykigLFQXSFSuNPM3D0CR9x0uf7/dtaxn0OoDYV+eTTGunsxNzr13GUr29ZpI7WsmBcvpnVQT+0ERHlH+VyWZmd0RvZQ5bi1gXjODYqwbJhwn7GknP0ZVMs3AvxdpUOsx+6GujX7IFP2Ttr9howlIPwEzC84vvoPE75d2sUbDHLXry3DnssOTgWJJiN7SfIvjrbMx6cvSNlYsEgwx6GOybEglepVbl69VpGxOMSo9u9441wd3Eyq++65rwf2mZC2aBpI6+0="

script:
  - ./gradlew test sonarqube